### PR TITLE
Add support for downscaler/force-uptime

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Look for any pods that have `downscaler/force-uptime` annotation set to `true`. If at least one is present, force the whole cluster back into uptime until the pods are terminated.

Change the default polling interval to 30 seconds so users don't need to wait too long for the scale-up to finish.

### CODE REVIEW

**Comment by dryewo** [comment]
How long does it actually take to start all the downscaled pods?
If we start a pod with this annotation, that starts running end-2-end tests immediately, the first bunch of tests will still fail because of that, no?

**Comment by aermakov-zalando** [comment]
@dryewo Yes, but I can't think of a proper solution. We don't know how long it'll take for all the stuff needed for e2e to come up, so I assume this is something the users would have to handle in the test suites.

**Comment by dryewo** [comment]
Fair enough.

**Comment by dryewo** [comment]
👍

**Pull request merged**
