### PR TITLE
Adds support for 'downtime-replicas' deployment annotation

### PR DESCRIPTION
**Pull request by jasongwartz**
Closes https://github.com/hjacobs/kube-downscaler/issues/22

Thought I'd use the above issue as a chance to check out pykube (which is awesome). Please let me know if there's any feedback!

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the contribution! I wonder if the naming is good or could be better, e.g. to be consistent with the usual "replicas" term. I don't have any strong opinion and I think "scale-down-to" is not bad, but some alternatives as food for thought:

* `downscaler/scale-down-to`
* `downscaler/target-replicas`
* `downscaler/desired-replicas`
* `downscaler/downscale-replicas`
* ...

I think it make sense to do one feedback loop about the naming as naming is hard and the decision is kind of permanent. I'm happy to hear other opinions.

**Comment by jasongwartz** [comment]
Yeah, great point - I definitely would want to make it a name that you think makes sense in the long-term. All of those sound good to me, which do you prefer most?

**Comment by hjacobs** [comment]
Let's see if @grebois has any opinion on the naming?

**Comment by grebois** [comment]
@hjacobs looks good to me, thanks for asking, one thing that you could add to this PR [here](https://github.com/hjacobs/kube-downscaler/blob/2e76ac09014883ecbb8455dd13e1722596e80d33/kube_downscaler/cmd.py) that would take fairly low effort would be something like:

```
    parser.add_argument('--scale-down-to',
                        help='Downscale specific deployment to X amount of replicas',
                        default=os.getenv('SCALE_DOWN_TO_ANNOTATION', ''))
```

what do you think?

**Comment by grebois** [comment]
btw, thanks a lot for the PR as well, really looking forward to this feature

**Comment by hjacobs** [comment]
@jasongwartz after thinking about it, I vote for `downscaler/downtime-replicas` as the annotation name, that's the least ambiguous (clear that it applies to the "downtime" state) and contains "replicas" (which seems to be the common terminology in Kubernetes world for such fields).

**Comment by hjacobs** [comment]
@grebois I don't think we need such CLI option to make the annotation name configurable. Or what was your intention?

**Comment by grebois** [comment]
it was just nice to have, also, regarding the name, maybe `downscaler/replicas` can also work

**Comment by jasongwartz** [comment]
@hjacobs nice one, `downtime-replicas` is great. I'll make that change today

**Comment by hjacobs** [comment]
@jasongwartz thanks!

**Pull request merged**
