### PR TITLE
Exclude namespaces with regex

### PR DESCRIPTION
**Pull request by mercantiandrea**
We have implemented a way to exclude namespaces via regex.
It is useful to exclude a group of namespaces without specify each namespace.

### CODE REVIEW

**Comment by mercantiandrea** [comment]
@hjacobs Could you please helm me in this merge?

**Comment by mercantiandrea** [comment]
@hjacobs Could you please helm me in this merge?

**Comment by hjacobs** [comment]
Can you add tests?

**Comment by mercantiandrea** [comment]
I’m not a developer, I will try to do it but I think that I will need your help :)

**Comment by hjacobs** [comment]
Replaced by #118

**Pull request closed without merging**
