### PR TITLE
Adding support for events

### PR DESCRIPTION
**Pull request by gregsidelinger**
Adding basic event support for https://github.com/hjacobs/kube-downscaler/issues/80.

Events on ScaleUp and ScaleDown are generated and show up when describing the object.  An event is also generated if the time spec value format is bad.  This way users are notified on a bad configuration if they do no have access to the controller logs.

### CODE REVIEW

**Comment by gregsidelinger** [comment]
I'm not sure how to get the coverage any higher.  Let me know if you have any concerns with the patch.

**Comment by gregsidelinger** [comment]
@hjacobs do you see any issues with this PR?  I can not get the coverage percentage higher as it is no longer hitting the old exception block on the one failure test for a bad time format since that triggers an event now.

**Comment by hjacobs** [comment]
@gregsidelinger thanks for the PR!

Can you make this behavior optional via a command line option? Not everybody might want to have event support (or grant rights to create events).

**Comment by gregsidelinger** [comment]
@hjacobs I can add a command line switch.  Do you want it off or on by default?  My vote is on but I like events as its a way for users who do not have access to the logs to get feed back. Especially for misconfigured date/time fields.

**Comment by hjacobs** [comment]
@gregsidelinger I also like events, but this might cause a lot of events for situations where `kube-downscaler` is "fighting" against another controller, i.e. where each downscale is reverted by a different controller. I have observed these situations and that's why I would make events opt-in.
Events should also be aggregated (count incremented).

**Comment by gregsidelinger** [comment]
@hjacobs I added an --enable-events flag and merged it with your latest changes.

I do have it looking up existing events and bumping the last seen timestamp and count for repeated events.  While testing I could not find any other way to have the count increment.  I'm not sure if there is a better way to do this using pykube. I use kube builder for all other controllers I have worked on and they have an event recorder which seems to take care of that for you.

**Comment by hjacobs** [comment]
Replaced by #127

**Pull request closed without merging**
